services:
  api:
    container_name: api
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
      - ../logs:/app/logs
    ports:
      - '3333:3333'
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://0.0.0.0:3333/ || exit 1']
      interval: 15s
      timeout: 10s
      retries: 3
